
POST http://localhost:3000/auth/register
content-type: application/json

{
  	"firstName": "John",
 	"lastName": "Smith",
 	"email": "johsdfn@gmail.com",
 	"password": "admin"
}

###

POST http://localhost:3000/auth/login
content-type: application/json

{
   "email": "johsdfn@gmail.com",
   "password": "admin"
}

###

POST http://localhost:3000/auth/refresh-token
content-type: application/json

{
	"refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjE2NTkzMDIwIiwiZW1haWwiOiJqb2hzZGZuQGdtYWlsLmNvbSIsInR5cGUiOiJyZWZyZXNoX3Rva2VuIiwiaWF0IjoxNjU5MzAyMDEzLCJleHAiOjE2NjE4OTQwMTN9.ryYZbefnYccn63XV1C4HweUffaPGrHWkQtna6aBjso8"
}
###

POST http://localhost:3000/auth/logout
content-type: application/json

{
	"refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjE2NTkzMDA4IiwiZW1haWwiOiJqb2hzZGZuQGdtYWlsLmNvbSIsInR5cGUiOiJyZWZyZXNoX3Rva2VuIiwiaWF0IjoxNjU5MzAwODM5LCJleHAiOjE2NjE4OTI4Mzl9.qaxO6Kv9VLfomrL7rLyG7CNzLqVMqKkr5cCaWc5_I4I"
}

###

POST http://localhost:3000/auth/change-password
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjE2NTkyOTMxIiwiZW1haWwiOiJqb2huQGdtYWlsLmNvbSIsInR5cGUiOiJhY2Nlc3NfdG9rZW4iLCJpYXQiOjE2NTkyOTMxMjEsImV4cCI6MTY1OTI5NjcyMX0.rolG0u_4WiotST2Z8dXDOwp3WafPCegWAWtpdgBGD8s

{
	"uid": "16592931",
   	"oldPassword": "admin",
   	"newPassword": "newpassword",
   	"confirmNewPassword": "newpassword"
}

