
GET http://localhost:8080/mailer
content-type: application/json


###

GET https://movie-list-backend-production.up.railway.app/movies/63609583de7191c4cf9b0202
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjE2NjY4ODQ2IiwiZW1haWwiOiJqb2hzZGZuQGdtYWlsLmNvbSIsImZpcnN0TmFtZSI6IkpvaG4iLCJsYXN0TmFtZSI6IlNtaXRoIiwidHlwZSI6ImFjY2Vzc190b2tlbiIsImlhdCI6MTY2Njg4NDY0MSwiZXhwIjoxNjY2ODg0NjcxfQ.4t7kyjQvrg67iX8ps971j6HE74ObHiEq35tghjDVv60


###

POST https://movie-list-backend-production.up.railway.app/movies
content-type: application/json
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjE2NjAwMzc5IiwiZW1haWwiOiJqb2hzZGZuQGdtYWlsLmNvbSIsImZpcnN0TmFtZSI6IkpvaG4iLCJsYXN0TmFtZSI6IlNtaXRoIiwidHlwZSI6ImFjY2Vzc190b2tlbiIsImlhdCI6MTY2MDAzODAwMywiZXhwIjoxNjYwMDM4MDMzfQ.59Y8IEMMJ5M_2mHpsGe0JqBN-XZ7DG4TnxHakqYH5aw

{
    "name" : "Top gun"
}
###

PATCH https://movie-list-backend-production.up.railway.app/movies/635a9f566a063dd2dccf98a8
content-type: application/json
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjE2NjAwMzc5IiwiZW1haWwiOiJqb2hzZGZuQGdtYWlsLmNvbSIsImZpcnN0TmFtZSI6IkpvaG4iLCJsYXN0TmFtZSI6IlNtaXRoIiwidHlwZSI6ImFjY2Vzc190b2tlbiIsImlhdCI6MTY2MDAzODAwMywiZXhwIjoxNjYwMDM4MDMzfQ.59Y8IEMMJ5M_2mHpsGe0JqBN-XZ7DG4TnxHakqYH5aw

{
    "name" : "Life of Pi 2"
}

###

DELETE https://movie-list-backend-production.up.railway.app/movies/63608df3c70f00beab35cd55
content-type: application/json
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjE2NjAwMzc5IiwiZW1haWwiOiJqb2hzZGZuQGdtYWlsLmNvbSIsImZpcnN0TmFtZSI6IkpvaG4iLCJsYXN0TmFtZSI6IlNtaXRoIiwidHlwZSI6ImFjY2Vzc190b2tlbiIsImlhdCI6MTY2MDAzODAwMywiZXhwIjoxNjYwMDM4MDMzfQ.59Y8IEMMJ5M_2mHpsGe0JqBN-XZ7DG4TnxHakqYH5aw

