
GET http://localhost:3000/movies
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjE2NTkzMDM1IiwiZW1haWwiOiJqb2hzZGZuQGdtYWlsLmNvbSIsInR5cGUiOiJyZWZyZXNoX3Rva2VuIiwiaWF0IjoxNjU5MzAzNTc0LCJleHAiOjE2NjE4OTU1NzR9.otOEgrMkn5cXOOPsY137yOfAkr69vt6RIGYrUYuHyTM


###

GET http://localhost:3000/movies/'1'
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjE2NTkzMDM5IiwiZW1haWwiOiJqb2hzZGZuQGdtYWlsLmNvbSIsInR5cGUiOiJyZWZyZXNoX3Rva2VuIiwiaWF0IjoxNjU5MzAzOTE5LCJleHAiOjE2NjE4OTU5MTl9.Fs_jV_Uv7UxBu_W5UgSMBLJVfnMQ8pRb7GY8YuNAOME


###
