
POST http://localhost:3000/auth/register
content-type: application/json

{
  	"firstName": "John",
 	"lastName": "Smith",
 	"email": "johsdfn@gmail.com",
 	"password": "admin"
}

###

POST http://localhost:3000/auth/login
content-type: application/json

{
   "email": "johsdfn@gmail.com",
   "password": "admin"
}

###

GET  http://localhost:3000/auth/test
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjE2NTk1NTE2IiwidXNlciI6eyJpZCI6IjE2NTk1NTE2IiwiZW1haWwiOiJqb2hzZGZuQGdtYWlsLmNvbSIsImZpcnN0TmFtZSI6IkpvaG4iLCJsYXN0TmFtZSI6IlNtaXRoIn0sInR5cGUiOiJhY2Nlc3NfdG9rZW4iLCJpYXQiOjE2NTk1NTE2NjgsImV4cCI6MTY1OTU1MTY3OH0.NVYVgWhfRN-O9wwhP4wJDrx77KhsGk5N2Ucu-Vgw9uI

{
	"testValue": "test"
}

###

POST http://localhost:3000/auth/refresh-token
content-type: application/json

{
	"refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjE2NTk1NTEzIiwidXNlciI6eyJpZCI6IjE2NTk1NTEzIiwiZW1haWwiOiJqb2hzZGZuQGdtYWlsLmNvbSIsImZpcnN0TmFtZSI6IkpvaG4iLCJsYXN0TmFtZSI6IlNtaXRoIn0sInR5cGUiOiJyZWZyZXNoX3Rva2VuIiwiaWF0IjoxNjU5NTUxNDI4LCJleHAiOjE2NjIxNDM0Mjh9.MmChJ-5waXW4wM0YDf3HcQpzKDsS85K4cKSYcCftckU"
}


###

POST http://localhost:3000/auth/logout
content-type: application/json

{
	"refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiMTY1OTU1MDMiLCJlbWFpbCI6ImpvaHNkZm5AZ21haWwuY29tIiwiZmlyc3ROYW1lIjoiSm9obiIsImxhc3ROYW1lIjoiU21pdGgifSwidHlwZSI6ImFjY2Vzc190b2tlbiIsImlhdCI6MTY1OTU1MDQ0NSwiZXhwIjoxNjU5NTUwNDU1fQ.Z2LKTAcV5jcm1UC30F57EjWhxLfSfOdIP0PW23kbneI"
}

###

POST http://localhost:3000/auth/change-password
content-type: application/json
Authorization: Bearer "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjE2NTk1NTEzIiwidXNlciI6eyJpZCI6IjE2NTk1NTEzIiwiZW1haWwiOiJqb2hzZGZuQGdtYWlsLmNvbSIsImZpcnN0TmFtZSI6IkpvaG4iLCJsYXN0TmFtZSI6IlNtaXRoIn0sInR5cGUiOiJhY2Nlc3NfdG9rZW4iLCJpYXQiOjE2NTk1NTE1MTAsImV4cCI6MTY1OTU1MTUyMH0.59akftI-3x5cOl2KbVcd95KgPTCLZMi-BiCG2AwkTUc"

{
	"uid": "16595516",
   	"oldPassword": "admin",
   	"newPassword": "newpassword",
   	"confirmNewPassword": "newpassword"
}

