
POST http://localhost:8080/auth/register
content-type: application/json

{
  	"firstName": "T",
 	"lastName": "K",
 	"email": "tanvirkhaan003@gmail.com",
 	"password": "admin"
}

###

POST http://localhost:8080/auth/login
content-type: application/json

{
   "email": "tanvirkhaan003@gmail.com",
   "password": "asdfasdf"
}

###

POST http://localhost:8080/auth/request-change-password
content-type: application/json

{
   "email": "tanvirkhaan003@gmail.com"
}
###

POST http://localhost:8080/auth/confirm-opt
content-type: application/json

{  
 	"email":"tanvirkhaan003@gmail.com",
   	"code": "9741"
}

###

POST  http://localhost:8080/auth/test
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzZTM5YTNlNGZkZmQ4Y2M0N2RmYmVlNCIsInR5cGUiOiJhY2Nlc3NfdG9rZW4iLCJpYXQiOjE2NzU4NzU3MjQsImV4cCI6MTY3NTg3NTc1NH0.nNlCsWULl5rDJmISxfW-amGycbhfjy_Mf05S2BAKRBI

{
	"test": "test"
}

###

POST http://localhost:8080/auth/refresh-token
content-type: application/json

{
	"refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzNjA5NmQ1MWVkNDNjMmFiYWI1MDVhZSIsInR5cGUiOiJyZWZyZXNoX3Rva2VuIiwiaWF0IjoxNjY3NDUxNTk3LCJleHAiOjE2NzAwNDM1OTd9.dJi8m2jTXDPtJryMiWkscANDmj1fior3zuZc2zQaKgU"
}


###

POST http://localhost:8080/auth/logout
content-type: application/json
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjE2NjAwMjMyIiwidXNlciI6eyJpZCI6IjE2NjAwMjMyIiwiZW1haWwiOiJqb2hzZGZuQGdtYWlsLmNvbSIsImZpcnN0TmFtZSI6IkpvaG4iLCJsYXN0TmFtZSI6IlNtaXRoIn0sInR5cGUiOiJhY2Nlc3NfdG9rZW4iLCJpYXQiOjE2NjAwMjMyOTQsImV4cCI6MTY2MDAyMzMyNH0.Y96WiY9CSk-4j12bcGHXN33fXHX2Vl8JC8YfXtySG68


###

POST http://localhost:8080/auth/change-password
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzZTM5YTNlNGZkZmQ4Y2M0N2RmYmVlNCIsInR5cGUiOiJhY2Nlc3NfdG9rZW4iLCJpYXQiOjE2NzU4NzYzNTgsImV4cCI6MTY3NTg3NjM4OH0.9tEA8wHSQKi1ad7hn80wrtlFtifVrZQecI69FkbVk5E


{

   	"uid": "63e39a3e4fdfd8cc47dfbee4",
   	"newPassword": "asdfasdf"
   
}

