
POST http://localhost:3000/auth/register
content-type: application/json

{
  	"firstName": "John",
 	"lastName": "Smith",
 	"email": "johsdfn@gmail.com",
 	"password": "admin"
}

###

POST http://localhost:3000/auth/login
content-type: application/json

{
   "email": "johsdfn@gmail.com",
   "password": "admin"
}

###

POST http://localhost:3000/auth/request-change-password
content-type: application/json

{
   "email": "johsdfn@gmail.com"
}

###

POST  http://localhost:3000/auth/test
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjE2NTk3ODM2IiwidXNlciI6eyJpZCI6IjE2NTk3ODM2IiwiZW1haWwiOiJqb2hzZGZuQGdtYWlsLmNvbSIsImZpcnN0TmFtZSI6IkpvaG4iLCJsYXN0TmFtZSI6IlNtaXRoIn0sInR5cGUiOiJhY2Nlc3NfdG9rZW4iLCJpYXQiOjE2NTk3ODM2NzQsImV4cCI6MTY1OTc4MzY4NH0.2n9FPunwuWNb4oGZap5Z46kYg4mfETylKo9DmHJTaAY

{
	"test": "test"
}

###

POST http://localhost:3000/auth/refresh-token
content-type: application/json

{
	"refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjE2NTk3ODQ2IiwidXNlciI6eyJpZCI6IjE2NTk3ODQ2IiwiZW1haWwiOiJqb2hzZGZuQGdtYWlsLmNvbSIsImZpcnN0TmFtZSI6IkpvaG4iLCJsYXN0TmFtZSI6IlNtaXRoIn0sInR5cGUiOiJyZWZyZXNoX3Rva2VuIiwiaWF0IjoxNjU5Nzg0NjY2LCJleHAiOjE2NjIzNzY2NjZ9.QQ28oZ1LVeXuv6nk32A5WQYfyNxpQnzIahm9yMdv79o"
}


###

POST http://localhost:3000/auth/logout
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjE2NjAwMjMyIiwidXNlciI6eyJpZCI6IjE2NjAwMjMyIiwiZW1haWwiOiJqb2hzZGZuQGdtYWlsLmNvbSIsImZpcnN0TmFtZSI6IkpvaG4iLCJsYXN0TmFtZSI6IlNtaXRoIn0sInR5cGUiOiJhY2Nlc3NfdG9rZW4iLCJpYXQiOjE2NjAwMjMyOTQsImV4cCI6MTY2MDAyMzMyNH0.Y96WiY9CSk-4j12bcGHXN33fXHX2Vl8JC8YfXtySG68


###

POST http://localhost:3000/auth/change-password
content-type: application/json
# Authorization: Bearer "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjE2NTk1NTEzIiwidXNlciI6eyJpZCI6IjE2NTk1NTEzIiwiZW1haWwiOiJqb2hzZGZuQGdtYWlsLmNvbSIsImZpcnN0TmFtZSI6IkpvaG4iLCJsYXN0TmFtZSI6IlNtaXRoIn0sInR5cGUiOiJhY2Nlc3NfdG9rZW4iLCJpYXQiOjE2NTk1NTE1MTAsImV4cCI6MTY1OTU1MTUyMH0.59akftI-3x5cOl2KbVcd95KgPTCLZMi-BiCG2AwkTUc"

{
	"token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImpvaHNkZm5AZ21haWwuY29tIiwidmVyaWZpY2F0aW9uQ29kZSI6Im0ycWNhOGVmbnJtZWdjYm9hNTV5dCIsInR5cGUiOiJjaGFuZ2VfcGFzc3dvcmQiLCJpYXQiOjE2NTk5ODQxNzMsImV4cCI6MTY1OTk4NDc3M30.VMMv0OiYEfS1hDQqSj2V1OIkeM26YreDN1QelyaNyWs",
	"email": "johsdfn@gmail.com",
   	"oldPassword": "admin",
   	"newPassword": "newpassword",
   	"confirmNewPassword": "newpassword"
}

